benchmark:
  jobs:
    - name: itransformer_net_injection_time_generalization
      run_name: itransformer_net_injection_time_generalization
      config: configs/baselines/itransformer_net_injection_time_generalization.yaml
    - name: informer_net_injection_time_generalization
      run_name: informer_net_injection_time_generalization
      config: configs/baselines/informer_net_injection_time_generalization.yaml
    - name: lstm_net_injection_time_generalization
      run_name: lstm_net_injection_time_generalization
      config: configs/baselines/lstm_net_injection_time_generalization.yaml
